version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-inventario
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql_data:/var/lib/mysql:rw